ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS actor_email VARCHAR(320);
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS outcome VARCHAR(32) NOT NULL DEFAULT 'SUCCESS';
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS ip_address VARCHAR(64);
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_agent VARCHAR(512);

