server:
  port: 8085

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/workflow_db}
    username: ${POSTGRES_USER:pfa_user}
    password: ${POSTGRES_PASSWORD:pfa_password}
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
