apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
  namespace: workflow-automation
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  AUTH_SERVICE_URI: http://auth-service:8081
  WORKFLOW_SERVICE_URI: http://workflow-service:8082