apiVersion: v1
kind: Secret
metadata:
  name: workflow-secret
  namespace: workflow-automation
type: Opaque
data:
  POSTGRES_USER: cGZhX3VzZXI=
  POSTGRES_PASSWORD: cGZhX3Bhc3N3b3Jk
  JWT_SECRET: bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=