server.port=${PORT:8082}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/workflow_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clean logs
spring.jpa.open-in-view=false

google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8082/api/integrations/google/callback}
google.oauth.scopes=${GOOGLE_GMAIL_SCOPES:https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}

# Gemini API Configuration
gemini.api-key=${GEMINI_API_KEY:AIzaSyBsfhdm8YIqvUespgXzPzOHKjT1Fdct7Jg}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
organization.service.url=${ORGANIZATION_SERVICE_URL:http://localhost:8083/api/organizations}