server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=pfa_user
spring.datasource.password=pfa_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clean logs
spring.jpa.open-in-view=false

google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8082/api/integrations/google/callback}
google.oauth.scopes=${GOOGLE_GMAIL_SCOPES:https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly}
