server.port=${PORT:8082}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/workflow_db}
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Clean logs
spring.jpa.open-in-view=false

# RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

app.rabbitmq.queue=${APP_RABBITMQ_QUEUE:workflow.execution.queue}
app.rabbitmq.exchange=${APP_RABBITMQ_EXCHANGE:workflow.execution.exchange}
app.rabbitmq.routingkey=${APP_RABBITMQ_ROUTINGKEY:workflow.execution.routingkey}

google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8082/api/integrations/google/callback}
google.oauth.scopes=${GOOGLE_GMAIL_SCOPES:https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}

# Gemini API Configuration
gemini.api-key=${GEMINI_API_KEY:AIzaSyBsfhdm8YIqvUespgXzPzOHKjT1Fdct7Jg}
gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
organization.service.url=${ORGANIZATION_SERVICE_URI:http://localhost:8083}/api/organizations

# Slack OAuth Configuration
slack.oauth.client-id=${SLACK_CLIENT_ID}
slack.oauth.client-secret=${SLACK_CLIENT_SECRET}
slack.oauth.redirect-uri=${SLACK_REDIRECT_URI:http://localhost:8082/api/integrations/slack/callback}
slack.oauth.scopes=${SLACK_SCOPES:chat:write,chat:write.public,channels:read}

# Notion OAuth Configuration
notion.oauth.client-id=${NOTION_CLIENT_ID}
notion.oauth.client-secret=${NOTION_CLIENT_SECRET}
notion.oauth.redirect-uri=${NOTION_REDIRECT_URI:http://localhost:8082/api/integrations/notion/callback}server.error.include-message=always
